version: 2
jobs:
  build:
    # machine: true
    # working_directory: ~/go/src/github.com/fnproject/fdk-node
    docker:
      - image: node 9.0
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      # install node
      - run: |
          curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - run: node -v
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "circle" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              # todo: login to npm
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              ./release.sh
            fi
